server:
  port: ${PORT_ANALYTIC}

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL_ANALYTIC}
    username: ${DB_USERNAME_ANALYTIC}
    password: ${DB_PASSWORD_ANALYTIC}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        default_schema: analytic
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update