services:
  api-gateway:
    image: andersomartins/api-gateway:latest
    container_name: api-gateway
    env_file: .env
    ports:
      - "${PORT_GATEWAY}:${PORT_GATEWAY}"
    networks:
      - agireport-network
    depends_on:
      - auth-service
      - history-service

  auth-service:
    image: andersomartins/auth-service:latest
    container_name: auth-service
    env_file: .env
    environment:
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE}
    ports:
      - "${PORT_AUTH}:${PORT_AUTH}"
    networks:
      - agireport-network

  history-service:
    image: andersomartins/history-service:latest
    container_name: history-service
    env_file: .env
    environment:
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE}
    ports:
      - "${PORT_HISTORY}:${PORT_HISTORY}"
    networks:
      - agireport-network

networks:
  agireport-network:
    driver: bridge
