name: Deploy VM1 (CI/CD)

on:
  push:
    branches:
      - main # Monitora a branch principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # Variáveis de ambiente: Mantemos apenas as de SSH e do diretório para o deploy
    env:
      VM_SSH_HOST: ${{ secrets.VM_SSH_HOST }}
      VM_SSH_USER: ${{ secrets.VM_SSH_USER }}
      VM_SSH_KEY: ${{ secrets.VM_SSH_KEY }}
      PROJECT_DIR: ~/agireport-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 1. Login Corrigido: Passa os Secrets DOCKERHUB_USERNAME e DOCKER_PASSWORD diretamente
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Passa o Secret diretamente
          password: ${{ secrets.DOCKER_PASSWORD }}   # Passa o Secret DOCKER_PASSWORD

      # 2. Build/Push Corrigido: Usa secrets.DOCKERHUB_USERNAME na sintaxe de shell
      - name: Build and push auth-service
        run: |
          # Acesso ao Secret diretamente na sintaxe ${{ secrets.NOME }}
          DOCKER_USER=${{ secrets.DOCKERHUB_USERNAME }}
          docker build -t $DOCKER_USER/auth-service:latest ./auth-service
          docker push $DOCKER_USER/auth-service:latest

      - name: Build and push history-service
        run: |
          DOCKER_USER=${{ secrets.DOCKERHUB_USERNAME }}
          docker build -t $DOCKER_USER/history-service:latest ./history-service
          docker push $DOCKER_USER/history-service:latest

      - name: Build and push api-gateway
        run: |
          DOCKER_USER=${{ secrets.DOCKERHUB_USERNAME }}
          docker build -t $DOCKER_USER/api-gateway:latest ./api-gateway
          docker push $DOCKER_USER/api-gateway:latest

      # 3. Deploy na VM: Usa as variáveis de ambiente (env) definidas no job
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ env.VM_SSH_HOST }}
          username: ${{ env.VM_SSH_USER }}
          key: ${{ env.VM_SSH_KEY }}
          script: |
            echo "Iniciando deploy na VM..."
            cd $PROJECT_DIR
            docker-compose pull
            docker-compose up -d
            echo "Deploy concluído."
