name: Deploy VM1

on:
  push:
    branches:
      - main  # ou a branch que você quiser monitorar

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      VM_SSH_HOST: ${{ secrets.VM_SSH_HOST }}           # ex: 164.152.192.160
      VM_SSH_USER: ${{ secrets.VM_SSH_USER }}           # ex: ubuntu
      VM_SSH_KEY: ${{ secrets.VM_SSH_KEY }}             # chave privada da VM
      PROJECT_DIR: ~/agireport-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push auth-service
        run: |
          docker build -t $DOCKERHUB_USERNAME/auth-service:latest ./auth-service
          docker push $DOCKERHUB_USERNAME/auth-service:latest

      - name: Build and push history-service
        run: |
          docker build -t $DOCKERHUB_USERNAME/history-service:latest ./history-service
          docker push $DOCKERHUB_USERNAME/history-service:latest

      - name: Build and push api-gateway
        run: |
          docker build -t $DOCKERHUB_USERNAME/api-gateway:latest ./api-gateway
          docker push $DOCKERHUB_USERNAME/api-gateway:latest

      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ env.VM_SSH_HOST }}
          username: ${{ env.VM_SSH_USER }}
          key: ${{ env.VM_SSH_KEY }}
          script: |
            cd $PROJECT_DIR
            docker-compose pull
            docker-compose up -d